import type { Metadata } from "next";
import { Montserrat , Cinzel_Decorative} from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import BackgroundWrapper from "../components/BackgroundWrapper";

import Footer from "@/components/Footer";


const cinzel = Cinzel_Decorative({
  subsets:['latin'],
  weight:["700"],
  variable:'--font-cinzel'
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Neila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${cinzel.variable} antialiased`}>
      <BackgroundWrapper>
        <Header />
        {children}

   
         <Footer />

      </BackgroundWrapper>
      </body>
    </html>
  );
}
