import type { Metadata } from "next";
import { Montserrat , Cinzel_Decorative} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Out_Now_Div from "@/components/Out_Now_Div";
import BackgroundWrapper from "@/components/BackgroundWrapper";

const cinzel = Cinzel_Decorative({
  subsets:['latin'],
  weight:["700"],
  variable:'--font-cinzel'
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.variable} ${cinzel.variable} antialiased`}>
      <BackgroundWrapper>
        <Header />
       
        {children}
        <Out_Now_Div />
        <Footer />
      </BackgroundWrapper>
      </body>
    </html>
  );
}
